Style changes on footer
OSWeekends/agenda pull request #71
Opened 2020-10-16 17:25 UTC by thamaragerigr

![image](https://user-images.githubusercontent.com/52920777/96289175-db3b7880-0fe4-11eb-8e65-362f425786b8.png)

Close #65

2020-10-16 22:00 UTC, baumannzone requested changes

2020-10-16 22:03 UTC, thamaragerigr commented on src/components/BaseFooter.vue
> +      Object.assign(document.bcreateElement('a'), {
claro, sorry T.T

2020-10-19 07:16 UTC, baumannzone approved these changes

2020-10-20 09:25 UTC, baumannzone commented
¿ Resuelves los conflictos @thamaragerigr ? No se que es lo que va o lo que no va

2020-10-20 17:05 UTC, merged